name = "DynamicProgramming"
uuid = "48fd7459-ece4-4749-a1ef-32f4cf5f58ae"
authors = ["Michele Fornino <fornino.michele@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
